### ISSUE TITLE
Consider Zulip/Discourse for communication?

### ISSUE THREAD

**Issue by matklad** [brioche-dev/brioche#53]
I see that brioche is using discord for communication, and I am wondering how strong is that decision. If you are confident in this choice, then I'll adapt! But if you are open to reconsidiration, I'll suggest taking a closer look at Zulip and Discourse. 

I am not sure whether is specific to me personally, or is a reflection of a wider demographics, but I can say that:

* I participate in a fair number of Zulip and discourse instances
* I mostly avoid Discord and matix, unless I absolutely have to

The main issue with Discord/IRC/matix for me is that I am _really_ not a fan of real-time communication, both because I am not in a US timezone, and because it's just psychologically easier for me to batch my communication. 

The secondary issue is that Discord just has too many features --- it's an advanced app which does all kinds of things, while, for technical communication, I really do prefer just to have a markdown text area.

Overall, my personal experience sums up to maybe 0.9 level of confidence that Zulip in particular fosters better technical communication. What I don't know though, is the strength of network effects. Maybe everyone except me is on Discrord already, which would lower the barrier to entry

I probably should have opened a discussion about this on Discord, but, for some reason, it fails to log me in :shrug: 

![image](https://github.com/brioche-dev/brioche/assets/1711539/36222f16-3b06-4a0b-97cc-51d717b93d7d)

**Comment by kylewlacy** [comment]
I was considering using Zulip instead of Discord, but ended up going with Discord because I figured it had more gravity! Also my wife has moderated Discord servers before and knows all the moderation tools really well, which was a big plus

But, I really like that Zulip has the ability to make channels that are readable on the open web (unlike Discord), so I decided to set up to give it a test drive: https://brioche.zulipchat.com/

(You'll still need a login to read it, I don't have the ability to make channels "web public" yet because I'm waiting on Zulip to respond to my request for an open source sponsorship)

I still consider Discord to be the "main hub", but I am totally fine trying out Zulip to see if it sticks. I also added a link to it on https://brioche.dev (but it's a temporary icon and doesn't show up in the header for docs because Starlight doesn't support it directly; see withastro/starlight#1952)
