### ISSUE TITLE
[LSP server] Question: how imports should be formatted ?

### ISSUE THREAD

**Issue by jaudiger** [brioche-dev/brioche#66]
I encountered both import statements in the repository https://github.com/brioche-dev/brioche-packages:

```ts
import { cargoBuild } from "rust";

// vs

import cargoBuild from "rust";
```

Both are valid, the point is more on: should we enforce one?

**Comment by jaudiger** [comment]
I'm in favor of consistency, but that's just me, I think.

**Comment by kylewlacy** [comment]
Ahh okay there's actually some method to the madness, let me try to explain 🙂

So quick background context: `import foo from "foo";` and `import { foo } from "foo";` mean two different things. The first means "import the export named `default` and give it the name `foo`", and the second means "import the export named `foo`". The equivalent exports would be `export default 123;` and `export default const foo = 123;`. The first import is really shorthand for `import { default as foo } from "foo";`

So with that context in mind, there are two problems we need to figure out:

1. When you call `brioche build` or similar commands, which function should get called and built by default?
2. When you import another package in your project, what's a good convention for the package itself?

For the first question, I decided that `brioche build` should call the `default` export. That wasn't the only choice, but it seemed like the most natural choice to me. That means when you define your package, you'd add a `default` export that defines the "main" package build: the thing that you want `brioche build` / `brioche run` / `brioche install` to use by default

...and, well, that kind of gives us an answer for our second question too! Every package now includes a default export, which is the "main" build for the package. So, dependent packages can just import the default export, and by convention we already know that's going to be the "main" build. That means it'll be a function that takes no arguments, and returns a recipe that will likely include a `bin` directory, and we can e.g. pass it to the `.dependencies()` method to use it in a process

As a convenience, I decided it'd also make sense to add extra "utility" exports for some packages. `cargoBuild` is the best example: it's a high-level wrapper that gives good defaults when doing a Rust/Cargo build, like caching the crate downloads and validating that the `Cargo.lock` file is up to date

So, if you see an export like `import rust, { cargoBuild } from "rust";`, I'm hoping the convention makes it clear that the default export (`rust`) is a function you can call without any arguments to get the "main" recipe for use as a dependency, and that `cargoBuild` is a utility function you can use as a higher-level wrapper

---

That still leaves open another option: adding a secondary named export. You could do something like this:

```ts
export function rust() {
  // ... main build ...
}
export default rust;
```

...but I decided against adopting this as a convention, since it'd be redundant with the `default` export, which would still be required

**Comment by jaudiger** [comment]
And that's why I said I was more a Rust guy than a Typescript guy. I definitively learned something today. Thanks for your thorough, well explained comment. I wasn't aware of the nuances with these import statements.

Everything is clear, and the choices you made are I think easily understandable by someone who is already aware of all of that.

I guess, I can simply close this ticket, since there is nothing more to do here!
